In [46]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv('../data/dataset.csv', index_col='id')
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [48]:
df.shape

(27, 8)

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 183721 to 183747
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  27 non-null     str
 1   favorites  26 non-null     float64
 2   retweets   26 non-null     float64
 3   mentions   26 non-null     float64
 4   country    27 non-null     str
 5   user       27 non-null     str
 6   followers  26 non-null     float64
 7   followees  27 non-null     int64
dtypes: float64(4), int64(1), str(3)
memory usage: 1.8 KB

In [50]:
df.describe()

        favorites    retweets   mentions   followers    followees
count   26.000000   26.000000  26.000000   26.000000    27.000000
mean   280.538462   80.000000  15.423077  352.807692  1190.185185
std    153.377242   40.303846   9.596554  375.319493  1965.735995
min     23.000000   21.000000   1.000000   12.000000   129.000000
25%    139.250000   45.500000   8.250000   21.000000   258.000000
50%    305.500000   79.000000  16.000000  332.000000   351.000000
75%    422.500000  110.750000  23.500000  389.000000  1822.000000
max    500.000000  146.000000  29.000000  982.000000  9918.000000

In [51]:
df_filtrado = df.dropna()
df_filtrado

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [52]:
df_filtrado = df.fillna(0)
df_filtrado.head(2)

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,0.0,BRASIL,mateusmartins,982.0,1822

In [53]:
df_filtrado = df.fillna({'retweets':0,'mentions':-1})
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [54]:
df['favorites']

id
183721     23.0
183722    500.0
183723    190.0
183724    131.0
183725    113.0
183726    492.0
183727    158.0
183728      NaN
183729    198.0
183730    272.0
183731     43.0
183732    349.0
183733    467.0
183734     50.0
183735    418.0
183736    361.0
183737    346.0
183738    296.0
183739    315.0
183740    133.0
183741     92.0
183742    255.0
183743    432.0
183744    430.0
183745    424.0
183746    488.0
183747    318.0
Name: favorites, dtype: float64

In [55]:
df['full_text']

id
183721    Flying home to run down from the power to comi...
183722                  Today we commemorate and MNML Case.
183723         Today we have reached US$6.55 Billion TT$44…
183724    Faking It by Joel Atwell. Written by Other cou...
183725                                      Welcome back! 🙌
183726    Contest: Win a fan of his ass. #thatisall Thanks!
183727                                   80's & friends! ✈️
183728    Thank you guess how did I feel somewhat offend...
183729          OnePlus 8 international giveaway classifies
183730                  Here it is.. Retweet this desperate
183731    Great to advertise during the year I tweeted a...
183732    Its been in love with the game with the origin...
183733                             Programming is the best!
183734                               I cannot believe this!
183735                               Buy this product NOW!!
183736    I have one is best color gradients: Just relea...
183737                                                PIC!!
183738                               hmmm feeling bad today
183739                            not feeling god right now
183740                          Programming is a hot topic!
183741                              Programming? i love it!
183742                                              WHAT???
183743                           Amazing video by Leonardo!
183744                                          Thanks man!
183745            There is nothing better than programming!
183746                                             BORED AF
183747    I do not know if i like programming or other t...
Name: full_text, dtype: str

In [56]:
df[['favorites','full_text']]

        favorites                                          full_text
id
183721       23.0  Flying home to run down from the power to comi...
183722      500.0                Today we commemorate and MNML Case.
183723      190.0       Today we have reached US$6.55 Billion TT$44…
183724      131.0  Faking It by Joel Atwell. Written by Other cou...
183725      113.0                                    Welcome back! 🙌
183726      492.0  Contest: Win a fan of his ass. #thatisall Thanks!
183727      158.0                                 80's & friends! ✈️
183728        NaN  Thank you guess how did I feel somewhat offend...
183729      198.0        OnePlus 8 international giveaway classifies
183730      272.0                Here it is.. Retweet this desperate
183731       43.0  Great to advertise during the year I tweeted a...
183732      349.0  Its been in love with the game with the origin...
183733      467.0                           Programming is the best!
183734       50.0                             I cannot believe this!
183735      418.0                             Buy this product NOW!!
183736      361.0  I have one is best color gradients: Just relea...
183737      346.0                                              PIC!!
183738      296.0                             hmmm feeling bad today
183739      315.0                          not feeling god right now
183740      133.0                        Programming is a hot topic!
183741       92.0                            Programming? i love it!
183742      255.0                                            WHAT???
183743      432.0                         Amazing video by Leonardo!
183744      430.0                                        Thanks man!
183745      424.0          There is nothing better than programming!
183746      488.0                                           BORED AF
183747      318.0  I do not know if i like programming or other t...

In [57]:
df.iloc[0:5]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [58]:
df.iloc[[0,2,8,9,10]]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822

In [64]:
df.loc[[183721,183723],['favorites','full_text']]

        favorites                                          full_text
id
183721       23.0  Flying home to run down from the power to comi...
183723      190.0       Today we have reached US$6.55 Billion TT$44…

In [65]:
df[df['favorites']>400]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

In [66]:
df[(df['favorites']>400) & (df['mentions']>20) ]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

In [67]:
df[df['full_text'].str.contains('programming')]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [68]:
import random
def calcularGanancias(retweets):
    ganancia = retweets * random.randint(3,5)
    return ganancia

df['ganancias'] = df['retweets'].apply(calcularGanancias)

df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees,ganancias
id,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258,NaN
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822,63.0
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129,615.0
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378,304.0
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129,520.0

In [70]:
df_filtrado = df.fillna(0)
df_filtrado

,full_text,favorites,retweets,mentions,country,user,followers,followees,ganancias
id,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258,0.0
183722,Today we commemorate and MNML Case.,500.0,21.0,0.0,BRASIL,mateusmartins,982.0,1822,63.0
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129,615.0
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378,304.0
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129,520.0
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822,210.0
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258,160.0
183728,Thank you guess how did I feel somewhat offend...,0.0,50.0,10.0,MEXICO,pedrojuarez,12.0,129,250.0
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129,328.0
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822,368.0
183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822,444.0
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822,220.0
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258,345.0
183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258,96.0
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721,72.0
183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129,368.0
183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351,345.0
183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721,279.0
183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378,104.0
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351,435.0
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378,730.0
183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378,219.0
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351,475.0
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,0.0,351,429.0
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351,330.0
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721,84.0
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918,174.0